### PR TITLE
v1.0.0 release

### PR DESCRIPTION
**Pull request by Atmelfan**
Major rewrite for a v1.0 release.

Todo:
- [x] Rewrite API to use generics 
- [x] Update documentation
  - [x] `scpi`
  - [x] `scpi-contrib`
- [x] Examples

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Hi,
 I am considering using this crate for a project of mine and I was wondering if I could do anything to help push 1.0 forward or simply stick to 0.4.0.

**Comment by Atmelfan** [comment]
Hello
I wouldn't recommend using 0.4, it relies on global variables/refcells for communication with the application and isn't very ergonomic. 1.0 is being refactored to use generics and more friendly for code-reuse.

The core `scpi ` crate needs updated documentation but have no major blocking tasks.
Mandatory commands and SCPI structures have been split out into a `scpi-contrib` crate, I planned to add some more abstractions for common SCPI subsystems (`MEASure`, `MMemory`, etc) but those can be pushed into a future release. 

I can probably release scpi 1.0 and the scpi-contrib 1.0 MVP during the coming week.

**Comment by MatthieuDartiailh** [comment]
Thanks for your quick answer.

For my specific use case the core scpi would already be quite useful. Apart from IEEE 488.2 command and some error reporting command I probably would not have much use for other standard commands. I may be able to contribute to the documentation as I work on my use case.

**Comment by Atmelfan** [comment]
Yes, arbitrary data blocks can be used like any other parameter. See example below:
```rust
struct MyCommand;

impl Command<MyDevice> for MyCommand {
    // Allow only query
    cmd_qonly!();

    fn query(
        &self,
        _device: &mut TestDevice,
        _context: &mut Context,
        mut params: Parameters,
        mut response: ResponseUnit,
    ) -> Result<()> {
        // Read a arbitrary data block
        // Example "MYCOMMAND #203ABC"
        let Arbitrary(data) = params.next_data()?;
        // Do something with data
        // ...
        // Write an arbitrary data block back
        response.data(Arbitrary(data)).finish()
    }
}
```

**Comment by MatthieuDartiailh** [comment]
Thanks !

**Comment by Atmelfan** [comment]
v1.0 have now been uploaded to crates.io.

**Comment by MatthieuDartiailh** [comment]
Great !

**Pull request merged**
