### PR TITLE
Update to Syn 2.0 and uom 0.36

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Update the derive macro to use Syn 2.0 and bump also uom.

### CODE REVIEW

**Comment by Atmelfan** [comment]
Sorry for the late response. I'll try to take a look at this during the weekend.

**Comment by MatthieuDartiailh** [comment]
No problem. I ran the CIs on my fork and everything is green (apart the coverage uploads).

**Comment by MatthieuDartiailh** [comment]
Friendly ping @Atmelfan (I know I can often forget about such things myself)

**Comment by Atmelfan** [comment]
Thank you @MatthieuDartiailh for the reminder

Version 1.0.1 has been published to crates.io.

Had to fix a some minor lint issues (the CI for linting was disabled for whatever reason...).

**Comment by MatthieuDartiailh** [comment]
Thanks for publishing the new version so fast !

**Pull request merged**
